/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : lha
 #	author : miyako
 #	2018/03/27
 #
 # --------------------------------------------------------------------------------*/

#include "lhasa.h"
#include "options.h"
#include "filter.h"
#include "extract.h"
#include "libjson.h"
#include "libjson_methods.h"

// --- lha
void LHA(sLONG_PTR *pResult, PackagePtr pParams);
